apiVersion: v1
kind: PersistentVolume
metadata:
  name: webigeo-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/"
  storageClassName: local-storage