apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: traefik
  tls:
    - secretName: app-secret
      hosts:
        - {{ .Values.DNS }}
        - {{ .Values.API_DNS}}
  rules:
  
  - host: {{ .Values.API_DNS}}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
             service:
              name: django-service
              port:
                number: 8000
