apiVersion: v1
kind: PersistentVolume
metadata:
  name: webigeo-pv-{{ .Values.mount }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/{{ .Values.mount }}"
  storageClassName: local-storage-{{ .Values.mount }}
